Plant.create(name: 'Aloe Vera', description: 'Aloe vera is a succulent plant species of the genus Aloe. It is widely distributed, and is considered an invasive species in many world regions. An evergreen perennial, it originates from the Arabian Peninsula, but grows wild in tropical, semi-tropical, and arid climates around the world.', price: 80.50, habitat: 'outdoor', trending: true, discount: 71.64, water: 'every 3 weeks', size: 100, picture: 'https://firebasestorage.googleapis.com/v0/b/plantie-e8be1.appspot.com/o/aloe-vera.png?alt=media&token=fcc429c1-2e96-4bb3-9974-fbdcb66d830c')

Plant.create(name: 'Chinese Evergreen', description: "This plant's leaves feature various shades of silver, gray, green, and even pink and red, making Chinese evergreen an excellent choice for brightening up low-light areas of your home.", price: 95.50, habitat: 'indoor', trending: true, new: true, discount: 87.50, water: 'every 2 days', size: 91.44, picture: 'https://firebasestorage.googleapis.com/v0/b/plantie-e8be1.appspot.com/o/aglaonema.png?alt=media&token=31500ed2-acc7-48a1-b313-e0ee9d4d54db')

Plant.create(name: 'Peperomia', description: "Peperomias are a diverse group of small, easy-care houseplants with waxy and often highly textured leaves. Some of our favorite varieties include ripple peperomia, watermelon peperomia, baby rubber plant, and silverleaf peperomia. ", price: 70.80, habitat: 'indoor', trending: true, discount: 56.64, water: 'every 3 days', size: 30.48, picture: 'https://firebasestorage.googleapis.com/v0/b/plantie-e8be1.appspot.com/o/peperomia.png?alt=media&token=d70b1ca6-b87e-4f85-be4a-49045f939a7f')

Plant.create(name: 'Grape Ivy', description: "'Ellen Danica,' the variety of grape ivy shown here is also called oakleaf ivy because its leaves are more deeply cut than other types of grape ivy. No matter which variety you choose, the shiny, deep green leaves will add an interesting texture to a room.", price: 86.99, habitat: 'outdoor', new: true, discount: 86.99, water: 'every 2 days', size: 182.88, picture: 'https://firebasestorage.googleapis.com/v0/b/plantie-e8be1.appspot.com/o/Grape-Ivy.png?alt=media&token=bea2f979-bb44-4032-88d4-3cd31fabca53')

Plant.create(name: 'Norfolk Island Pine', description: "Outdoors, a new tree can be a big investment, but easy indoor trees can make affordable yet eye-catching houseplants for beginners. The secret to keeping Norfolk Island pine healthy indoors is to give it bright but indirect light. In low light, the lower branches tend to turn brown and fall off. This plant's soft texture adds a cozy, woodsy feeling to any room.", price: 86.99, habitat: 'indoor', trending: true, discount: 73.94, water: 'every 3 days', size: 304.8, picture: 'https://firebasestorage.googleapis.com/v0/b/plantie-e8be1.appspot.com/o/NorfolkIslandPine.png?alt=media&token=f274357b-881e-4c68-835c-1b47f1717152')

Plant.create(name: 'Dieffenbachia', description: "Several closely related species share the name of dieffenbachia; they've all got canelike stems and lush green foliage variegated in white or cream. Its large, green-and-white leaves add a tropical touch to any room of your home.", price: 102.50, habitat: 'indoor', trending: true, new: true, discount: 102.50, water: 'every 2 days', size: 182.88, picture: 'https://firebasestorage.googleapis.com/v0/b/plantie-e8be1.appspot.com/o/dieffenbachia.png?alt=media&token=f1603ab7-5548-4370-a468-c0ebc35c4f91')

Plant.create(name: 'Snake Plant', description: "This easy succulent plant seems almost indestructible. Snake plant tolerates low light and little water while still maintaining its good looks. You can find several different varieties with different leaf shapes and patterns like the one shown here.", price: 63.50, habitat: 'outdoor', trending: true, discount: 47.63, water: 'every 3 days', size: 121.92, picture: 'https://firebasestorage.googleapis.com/v0/b/plantie-e8be1.appspot.com/o/snake-plant.png?alt=media&token=15870a7b-40db-4e3c-ac87-b9a8705da8e0')

Plant.create(name: 'Rubber Tree', description: "A classic houseplant, rubber tree gets its name from the sticky, milky sap it exudes from cuts. It can eventually grow into a large tree, but you can easily keep it shorter by pruning back long stems, causing it to branch into a multi-stemmed shrub.", price: 79.50, habitat: 'indoor', new: true, water: 'every 3 days', discount: 79.50, size: 243.84, picture: 'https://firebasestorage.googleapis.com/v0/b/plantie-e8be1.appspot.com/o/Rubber-Plant.png?alt=media&token=25f26923-d5c4-482d-823a-c699f71aafed')

Plant.create(name: 'Calathea', description: "Calathea or prayer plant will draw attention no matter where you place it, thanks to its boldly striped leaves. There are plenty of varieties to choose from, some with rose, white, or yellow leaves.", price: 130.40, habitat: 'indoor', discount: 130.40, water: 'every 2-7 days', size: 182.88, picture: 'https://firebasestorage.googleapis.com/v0/b/plantie-e8be1.appspot.com/o/calathea-plant.png?alt=media&token=73878737-e4f3-473e-a037-f21c6e8c9f5d')

Plant.create(name: 'Columnea', description: "One look at columnea's bright orange blooms, and you'll know why its common name is goldfish plant. You'll usually start to see flowers appearing in the spring and summer, but even when it's not in bloom, this plant's glossy, dark green foliage is beautiful all on its own.", price: 110.60, habitat: 'outdoor', trending: true, discount: 77.42, water: 'every 3 days', size: 548.64, picture: 'https://firebasestorage.googleapis.com/v0/b/plantie-e8be1.appspot.com/o/Columnea.png?alt=media&token=f47cd53a-6594-4cc1-b0b1-b7f15596e692')

Plant.create(name: 'Blue Salvia', description: "A favorite plant for many gardeners, blue salvia is an easy perennial to grow. It flowers profusely all summer, and tolerates periods of drought. It's a great choice for borders and containers, plus it's native to areas of North America.", price: 98.70, habitat: 'outdoor', discount: 98.70, water: 'every 2 days', size: 91.44, picture: 'https://firebasestorage.googleapis.com/v0/b/plantie-e8be1.appspot.com/o/Blue-Salvia.png?alt=media&token=5cdc7f08-4da0-433a-86d9-b5a2e108c584')

Plant.create(name: 'Glossy Abelia', description: "Butterflies love the fragrant, trumpet-shape flowers that dangle all summer long from glossy abelia's branches. This flowering hedge plant naturally forms a tall arching mound, but you can prune it in late winter to early spring to create a lower hedge.", price: 97.50, habitat: 'outdoor', discount: 97.50, water: 'every 2 days', size: 182.88, picture: 'https://firebasestorage.googleapis.com/v0/b/plantie-e8be1.appspot.com/o/Glossy-Abelia.png?alt=media&token=b7ec740a-d9f7-40f7-ac68-df114645ce1e')

Plant.create(name: 'Flowering Quince', description: "Light up the early spring landscape with the scarlet, pink, or white blooms of flowering quince. This deciduous shrub is equipped with sharp spines that make it an effective barrier plant or privacy screen.", price: 86.99, habitat: 'outdoor', new: true, discount: 86.99, water: 'every 2 days', size: 304.8, picture: 'https://firebasestorage.googleapis.com/v0/b/plantie-e8be1.appspot.com/o/Flowering-Quince.png?alt=media&token=e59ba414-fa83-4ab7-a74d-b73429925dc3')